<?php

use Drupal\Core\Form\FormStateInterface;


function adv_form_form_alter (&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'node_article_form') {

    $config = \Drupal::config('adv_form.settings');
    $title = $config->get('title');
    $advanced = $config->get('advanced');
    $tags = $config->get('tags');
    $term = \Drupal\taxonomy\Entity\Term::load($tags);

      // print_r($form['field_tags']['widget']['target_id']); exit;


    if (!empty($title)) {
      $form['title']['widget'][0]['value']['#default_value'] = $title;
    }
    if (!empty($advanced)) {
      $form['field_advanced']['widget']['value']['#default_value'] = $advanced;
    }
        if (!empty($tags)) {
      $form['field_tags']['widget']['target_id']['#default_value'] = $term;

      // print_r($form['field_tags']['widget']['target_id']['#default_value']); exit;
    }

  }

}
